INSERT INTO oeuvres VALUES
	(1,'Narcisse et Goldmund','Hermann HESSE', 1930, 'Roman'),
	(2,'Bérénice','Jean RACINE', 1670, 'Théâtre'),
	(3,'Prolégomènes à  toute métaphysique future','Emmanuel KANT', 1783, 'Philosophie'),
	(4,'Mon coeur mis à nu','Charles BAUDELAIRE', 1887, 'Journal'),
	(5,'Voyage au bout de la nuit','Louis-Ferdinand CELINE', 1932, 'Roman'),
	(6,'Les possédés','Fedor DOSTOIEVSKI', 1872, 'Roman'),
	(7,'Le Rouge et le Noir','STENDHAL', 1830, 'Roman'),
	(8,'Alcibiade','Jacqueline de ROMILLY', 1995, 'Roman'),
	(9,'Monsieur Teste','Paul VALERY', 1926, 'Roman'),
	(10,'Lettres de Gourgounel','Kenneth WHITE', 1979, 'Récit'),
	(11,'Lettres à un jeune poète','Rainer Maria RILKE', 1929, 'Lettre'),
	(12,'Logique sans peine','Lewis CAROLL', 1887, 'Logique'),
	(13,'L''éthique','Baruch SPINOZA', 1677, 'Philosophie'),
	(14,'Sur le rêve','Sigmund FREUD', 1900, 'Philosophie'),
	(15,'Sens et dénotation','Gottlob FREGE', 1892, 'Philosophie'),
	(16,'Penser la logique','Gilbert HOTTOIS', 1989, 'Philosophie'),
	(17,'Au coeur des ténèbres','Joseph CONRAD',1899, 'Roman'),
	(18,'Jan Karski','Yannick HAENEL', 2009, 'Roman');	
